### ISSUE TITLE
イベント一覧画面のToolbarとタブ部分の作成

### ISSUE THREAD

**Issue by iroha-168** [iroha-168/PickUpAndroidEvent#2]
# 詳細
イベント一覧画面は画像のようにToolbar, 切り替えタブ, リストの大きく３つのViewで構成されている。
今回はリスト以外のToolbarと切り替えタブをcomposeで構成していく。

<img src="https://user-images.githubusercontent.com/67794229/173839488-f2b29db2-503a-4549-8547-cc880dc9eb29.jpg" width=60%>

**Comment by dosukoi-android** [comment]
👍
